# Generated by Django 5.0.1 on 2024-02-09 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0002_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
