# Generated by Django 4.2 on 2024-02-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0005_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='icecream',
            name='slug',
            field=models.SlugField(default='', max_length=255),
        ),
    ]
