# Generated by Django 4.2 on 2024-02-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0007_alter_icecream_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icecream',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
